{% set name = "dagmc" %}
{% set version = "3.2.1" %}
{% set sha256 = "2cd2683fbcb4ae30eed2393741e320c7b1403e9a80d1af6306c2042a06775801" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/svalinn/DAGMC/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - hdf5
    - moab 5.3.1
    - eigen
  run:
    - hdf5
    - moab 5.3.1
    - zlib

test:
   commands:
     - make_watertight --help

about:
  home: https://svalinn.github.io/DAGMC/
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Direct Accelerated Geometry Toolkit'

extra:
  recipe-maintainers:
    - gonuke
    - pshriwise
    - ljacobson64
    - kkiesling
    - bam241
    - ngranda
    - shimwell
