{% set name = "dagmc" %}
{% set version = "3.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/svalinn/DAGMC.git
  git_rev: v{{ version }}
  git_depth: 1 # (Defaults to -1/not shallow)


build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - eigen
    - moab * nompi_tempest*
  run:
    - moab * nompi_tempest*
    - zlib

test:
   commands:
     - make_watertight --help

about:
  home: https://svalinn.github.io/DAGMC/
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: 'Direct Accelerated Geometry Toolkit'
  description: |
    Direct Accelerated Geometry Monte Carlo (DAGMC) is a software package that
    allows users to perform Monte Carlo radiation transport directly on CAD
    models.
  dev_url: https://github.com/svalinn/DAGMC

extra:
  recipe-maintainers:
    - gonuke
    - pshriwise
    - ljacobson64
    - kkiesling
    - bam241
    - ngranda
    - shimwell
